notes/urls.py
from django.contrib import admin
from django.urls import path , include , re_path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('accounts.urls',namespace='home')),
    path('notes/' , include('notes_app.urls' ,namespace = 'notes') ),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_app/urls.py
from django.urls import path , include , re_path as url

from . import views
from . import api_views

app_name = 'notes_app'

urlpatterns = [
    path('' , views.notelist , name='post_list'),
    path('id=<int:id>/' , views.post_details , name='post_detail'),
    path('tags/<str:slug>' , views.PostByTags.as_view() , name='post_by_tags'),
    path('add/' ,views.note_add , name='add_note'),
    path('<int:id>/edit' , views.edit,name='note_edit'),
    path('<int:id>/delete' , views.delete_note,name='delete_note'),
    ## api urls ##
    path('api/list' , api_views.NotesListApi.as_view(), name='notes_api_list'),
    # path('api/list' , api_views.post_list, name='notes_api_list'),
    # path('api/list/<int:id>' , api_views.post_deatils_api, name='notes_api_details'),
    # path('api/list/<str:query>' , api_views.searchByTag, name='searchByTag'),
    path('api/list/<int:pk>' , api_views.NotesDetailsApi.as_view(), name='notes_api_detail')
    
]

notes_app/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager

class Note(models.Model):   
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField( max_length=50)
    slug = models.SlugField(null=True , blank=True)
    content = models.TextField(max_length=2000 , blank=True)
    craeted = models.DateTimeField( default=timezone.now ,null=True, blank=True)
    active = models.BooleanField(default=True)
    tags = TaggableManager()
    img = models.ImageField(upload_to="notes-img")

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note,self).save( *args , **kwargs)

    def get_absolute_url(self):
        return reverse("notes_app:post_detail", kwargs={"id":self.id})


    def __str__(self):
        return self.title
    

notes_app/forms.py
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title' , 'content' , 'tags' , 'img' ]

notes_app/views.py
from django.shortcuts import get_object_or_404, render , redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import Note 
from .forms import NoteForm
from django.views.generic import ListView ,DetailView
from django.db.models.query_utils import Q
from django.db.models import Count
from django.contrib import messages
from django.core.paginator import Paginator
from taggit.models import Tag




def notelist(request):
    user = request.user
    my_notes = Note.objects.filter(user=user).order_by('-craeted')
    paginator = Paginator(my_notes, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, 'notes.html',{
        'user' : user ,
        'page_obj' : page_obj
    })

def post_details(request,id):
    user = request.user
    note=Note.objects.get(id=id,user=user)
    recent_posts = Note.objects.filter(user=user).order_by('-craeted')[:9]
    tags = Tag.objects.all()
    context = {
        'note':note,
        'recent_posts':recent_posts,
        'tags':tags
    }
    return render(request,'notes_details.html',context)

class PostByTags(ListView):
    model = Note
    template_name = 'notes_by_tags.html'
    paginate_by=3


    def get_queryset(self) :
        slug = self.kwargs['slug']
        object_list = Note.objects.filter(
            Q(tags__name__icontains = slug),
        )
        return object_list.filter(user=self.request.user)

    
def note_add(request):
        if request.method == "POST" :
            form = NoteForm(request.POST,request.FILES)

            if form.is_valid():
                new_form = form.save(commit=False)
                new_form.user = request.user
                new_form.save()
                form.save_m2m()
                messages.success(request, "Note Is Added Succssefully.")
                return redirect('/notes')

        else:
            form = NoteForm
        context = {
            'form' : form ,
        }
        
        return render(request, 'add.html' , context)


def edit(request ,id):
    note = get_object_or_404(Note , id=id)
    if request.method == "POST" :
        form = NoteForm(request.POST , instance=note)

        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            form.save_m2m()
            messages.success(request, "Note Is Updated Succssefully.")
            return redirect('/notes')

    else:
        form = NoteForm(instance=note)
    context = {
        'form' : form
    }
    


    return render(request, 'create.html' , context)

def delete_note(request , id):
    note = get_object_or_404(Note , id=id)
    context = {'post': note}    
    
    if request.method == 'GET':
        return render(request, 'post_confirm_delete.html',context)
    elif request.method == 'POST':
        note.delete()
        messages.success(request,  'The post has been deleted successfully.')
        return redirect('/notes')

    

notes_app/templates/add.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}<br><br><br><br>


<div class="container">
    <div class="add_form">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {%bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Add Note" %}
        </form>
    </div>
</div><br><br>
{% endblock body %}

notes_app/templates/create.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}<br><br><br><br>
<div class="container">
    <div class="edit_form">
        <form method="POST">
            {% csrf_token %}
            {%bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Edit Note" %}
        </form>
    </div>
</div><br><br><br>
{% endblock body %}

notes_app/templates/notes.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<style>
  .button_styles {
    text-align: center;
    padding-top: 10px;
  }

  .button_styles2 {
    padding-bottom: 5px;
  }

  .A1 {
    text-decoration: none;
    color: white;
    background: #3545dc;
    padding: 1px 4px;
    border-radius: 4px;
    font-size: 19px;
    margin-right: 10px;
    margin-bottom: 15px;
  }
  .A2 {
    text-decoration: none;
    color: white;
    background: #3545dc;
    padding: 1px 4px;
    border-radius: 4px;
    font-size: 19px;
    margin-left: 10px;
    margin-bottom: 5px;
  }

  .A1:hover {
    background:  rgp(0, 51, 102);
    color:white;
  }
  .A2:hover {
    background:  rgp(0, 51, 102);
    color:white;
  }

  .A1:focus {
    outline: 3px solid rgb(220 53 69 / 50%);

  }
  .A2:focus {
    outline: 3px solid rgb(220 53 69 / 50%);

  }

  .justify-content-center {
    display: flex;
    justify-content: space-between;
  }
</style>

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>My Notes</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li> My Notes</li>
        </ol>
      </div>

    </div>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row g-5">

        <div class="col-lg-12">

          <div class="row gy-4 posts-list">
            {% for note in page_obj %}
            <div class="col-lg-4">
              <article class="d-flex flex-column">
                {% if note.img %}
                <div class="post-img">
                  <img src="{{note.img.url}}" alt="" class="img-fluid">
                </div>
                {% else %}
                <img src="{% static 'C:\New folder (2)\django\Notes\src\static\assets\img\default.jpg' %}" alt=""
                  class="img-fluid">
                {% endif %}
                <h2 class="title">
                  <a href="{{note.get_absolute_url}}">{{note}}</a>
                </h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                        href="{{note.get_absolute_url}}">{{note.user.username}}</a></li>
                        {% for tag in note.tags.all %}
                    <li class="d-flex align-items-center"><i class="bi bi-tags"></i> <a
                        href="{% url 'notes_app:post_by_tags' tag%}">{{tag}}</a></li>
                        {% endfor %}
                  </ul>
                </div>
                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                        href="{{note.get_absolute_url}}"><time datetime="2020-01-01">{{note.craeted}}</time></a></li>
                  </ul>
                </div>
                <div class="content">
                  <p>
                    {{note.content|truncatewords:'20'}}
                  </p>
                </div>

                <div class="read-more mt-auto align-self-end" style="padding-right: 122.5px;">
                  <a href="{{note.get_absolute_url}}">Read More</a>
                </div>
                <div class="read-more mt-auto align-self-first" style="padding-left: 100px;
                padding-top:5px;">
                  <a href="{% url 'notes:delete_note' note.id  %}">Delete Note</a>
                </div>

              </article>
            </div><!-- End post list item -->
            {% endfor %}
            <div class="button_styles">
              <a href="{% url 'notes:add_note' %}">
                {% bootstrap_button button_type="submit" content="Add Note" %}</a>
            </div>

          </div>

          <!-- End blog posts list -->

          <div class="blog-pagination">
            <ul class="justify-content-center">
              {% if page_obj.has_previous %}
              <a class ="A1" href="?page={{ page_obj.previous_page_number }}">&laquo;previous</a>
              {% endif %}

              <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
              </span>

              {% if page_obj.has_next %}
              <a class ="A2" href="?page={{ page_obj.next_page_number }}">next&raquo;</a>
              {% endif %} </ul>
          </div><!-- End blog pagination -->

        </div>


      </div>

    </div>

    </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->
{% endblock body %}

notes_app/templates/notes_by_tags.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<style>
  .button_styles {
    text-align: center;
    padding-top: 10px;
  }

  .button_styles2 {
    padding-bottom: 5px;
  }

  .A1 {
    text-decoration: none;
    color: white;
    background: #3545dc;
    padding: 1px 4px;
    border-radius: 4px;
    font-size: 19px;
    margin-right: 10px;
    margin-bottom: 15px;
  }
  .A2 {
    text-decoration: none;
    color: white;
    background: #3545dc;
    padding: 1px 4px;
    border-radius: 4px;
    font-size: 19px;
    margin-left: 10px;
    margin-bottom: 5px;
  }

  .A1:hover {
    background:  rgp(0, 51, 102);
    color:white;
  }
  .A2:hover {
    background:  rgp(0, 51, 102);
    color:white;
  }

  .A1:focus {
    outline: 3px solid rgb(220 53 69 / 50%);

  }
  .A2:focus {
    outline: 3px solid rgb(220 53 69 / 50%);

  }

  .justify-content-center {
    display: flex;
    justify-content: space-between;
  }
</style>

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>My Notes</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li> My Notes</li>
        </ol>
      </div>

    </div>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row g-5">

        <div class="col-lg-12">

          <div class="row gy-4 posts-list">
            {% for note in object_list %}
            <div class="col-lg-4">
              <article class="d-flex flex-column">
                {% if note.img %}
                <div class="post-img">
                  <img src="{{note.img.url}}" alt="" class="img-fluid">
                </div>
                {% else %}
                <img src="{% static 'C:\New folder (2)\django\Notes\src\static\assets\img\default.jpg' %}" alt=""
                  class="img-fluid">
                {% endif %}
                <h2 class="title">
                  <a href="{{note.get_absolute_url}}">{{note}}</a>
                </h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                        href="{{note.get_absolute_url}}">{{note.user.username}}</a></li>
                        {% for tag in note.tags.all %}
                    <li class="d-flex align-items-center"><i class="bi bi-tags"></i> <a
                        href="{% url 'notes_app:post_by_tags' tag%}">{{tag}}</a></li>
                        {% endfor %}
                  </ul>
                </div>
                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                        href="{{note.get_absolute_url}}"><time datetime="2020-01-01">{{note.craeted}}</time></a></li>
                  </ul>
                </div>
                <div class="content">
                  <p>
                    {{note.content|truncatewords:'20'}}
                  </p>
                </div>

                <div class="read-more mt-auto align-self-end" style="padding-right: 122.5px;">
                  <a href="{{note.get_absolute_url}}">Read More</a>
                </div>
                <div class="read-more mt-auto align-self-first" style="padding-left: 100px;
                padding-top:5px;">
                  <a href="{% url 'notes:delete_note' note.id  %}">Delete Note</a>
                </div>

              </article>
            </div><!-- End post list item -->
            {% endfor %}
            <div class="button_styles">
              <a href="{% url 'notes:add_note' %}">
                {% bootstrap_button button_type="submit" content="Add Note" %}</a>
            </div>

          </div>

          <!-- End blog posts list -->

          <div class="blog-pagination">
            <ul class="justify-content-center">
              {% if page_obj.has_previous %}
              <a class ="A1" href="?page={{ page_obj.previous_page_number }}">&laquo;previous</a>
              {% endif %}

              <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
              </span>

              {% if page_obj.has_next %}
              <a class ="A2" href="?page={{ page_obj.next_page_number }}">next&raquo;</a>
              {% endif %} </ul>
          </div><!-- End blog pagination -->

        </div>


      </div>

    </div>

    </div>
  </section><!-- End Blog Section -->

</main><!-- End #main -->
{% endblock body %}

notes_app/templates/notes_details.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}

<style>
  .button_styles {
    text-align: center;
    padding-top: 10px;
  }
</style>



<main id="main">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Note Details</h2>
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'notes_app:post_list' %}">Notes</a></li>
          <li>Note Details</li>
        </ol>
      </div>

    </div>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Blog Details Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">

      <div class="row g-5">

        <div class="col-lg-8">

          <article class="blog-details">
            {% if note.img %}
            <div class="post-img">
              <img src="{{note.img.url}}" alt="" class="img-fluid">
            </div>
            {% else %}
            <img src="{% static 'C:\New folder (2)\django\Notes\src\static\assets\img\default.jpg' %}" alt=""
              class="img-fluid"> {% endif %}

            <h2 class="title">{{note.title}}</h2>

            <div class="meta-top">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                    href="{{note.get_absolute_url}}">{{note.user.username}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                    href="{{note.get_absolute_url}}"><time datetime="2020-01-01">{{note.craeted}}</time></a></li>
              </ul>
            </div><!-- End meta top -->

            <div class="content">
              <p>
                {{note.content}}
              </p>

            </div><!-- End post content -->

            <div class="meta-bottom">


              <i class="bi bi-tags"></i>
              <ul class="tags">
                {% for tag in note.tags.all %}
                <li><a href="{% url 'notes_app:post_by_tags' tag %}">{{tag}}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="button_styles">
              <a href="{% url 'notes:note_edit' note.id %}">
                {% bootstrap_button button_type="submit" content="Edit Note" %}</a>
            </div>
            <div class="button_styles">
              <a href="{% url 'notes:delete_note' note.id %}">
                {% bootstrap_button button_type="submit" content="Delete Note" %}</a>
            </div>

          </article><!-- End blog post -->


        </div>

        <div class="col-lg-4">

          <div class="sidebar">


            <div class="sidebar-item recent-posts">
              <h3 class="sidebar-title">Recent Posts</h3>

              <div class="mt-3">

                {% for post in recent_posts  %}

                <div class="mt-3">

                  <div class="post-item mt-3">
                    {% if post.img %}
                    <div class="post-img">
                      <img src="{{post.img.url}}" alt="" class="img-fluid">
                    </div>
                    {% else %}
                    <img src="{% static 'C:\New folder (2)\django\Notes\src\static\assets\img\default.jpg' %}" alt=""
                      class="img-fluid"> {% endif %}
                    <img src="{{post.image.url}}" alt="" class="flex-shrink-0">
                    <div>
                      <h4><a href="{{post.get_absolute_url}}">{{post}}</a></h4>
                      <time datetime="2020-01-01">{{post.craeted}}</time>
                    </div>
                  </div><!-- End recent post item-->
                  {% endfor %}


                </div>

              </div><!-- End sidebar recent posts-->

            </div><br><!-- End Blog Sidebar -->
            <div class="sidebar-item tags">
                <h3 class="sidebar-title">Tags</h3>
                <ul class="mt-3">
                  {% for tag in tags %}
                  <li><a href="{% url 'notes_app:post_by_tags' tag %}">{{tag}}</a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

          </div>
        </div>

      </div>
  </section><!-- End Blog Details Section -->

</main><!-- End #main -->
{% endblock body %}

notes_app/templates/post_confirm_delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}


{% block body %}
<style>
    .delete_form {
        margin-top: 150px;
        margin-bottom: 100px;
    }
</style>
<div class="delete_form">
    <h2 style="text-align:center;">Delete Post</h2>
    <form method="POST">
        <div class="containers">
            <div class="col-md-6 mx-auto mt-5">
                {% csrf_token %}
                <p>Are you sure that you want to delete the post ?</p>
                <div>
                    {% bootstrap_button button_type="submit" content="Yes , Delete" %}
                    <a href="{% url 'notes:post_list' %}">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>


{% endblock body %}