accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'

urlpatterns = [
    path('', views.home ,name = 'home'),
    path('signup' , views.signup , name='signup'),
    path('profile/' , views.profile , name='profile'),
    path('profile/edit' , views.edit_profile , name='edit_profile'),
    path('newsletter/' , views.news_letters_subscribe , name = 'newsletter'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
]

notes/urls.py
from django.contrib import admin
from django.urls import path , include , re_path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('accounts.urls',namespace='home')),
    path('notes/' , include('notes_app.urls' ,namespace = 'notes') ),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_app/urls.py
from django.urls import path , include , re_path as url

from . import views
from . import api_views

app_name = 'notes_app'

urlpatterns = [
    path('' , views.notelist , name='post_list'),
    path('id=<int:id>/' , views.post_details , name='post_detail'),
    path('tags/<str:slug>' , views.PostByTags.as_view() , name='post_by_tags'),
    path('add/' ,views.note_add , name='add_note'),
    path('<int:id>/edit' , views.edit,name='note_edit'),
    path('<int:id>/delete' , views.delete_note,name='delete_note'),
    ## api urls ##
    path('api/list' , api_views.NotesListApi.as_view(), name='notes_api_list'),
    # path('api/list' , api_views.post_list, name='notes_api_list'),
    # path('api/list/<int:id>' , api_views.post_deatils_api, name='notes_api_details'),
    # path('api/list/<str:query>' , api_views.searchByTag, name='searchByTag'),
    path('api/list/<int:pk>' , api_views.NotesDetailsApi.as_view(), name='notes_api_detail')
    
]

accounts/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.urls import reverse




class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    headline = models.CharField(max_length=50 , blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='users/', null=True, blank=True )
    join_date = models.DateTimeField( default=datetime.datetime.now())
    fb_link = models.URLField( max_length=200, blank=True, null=True)
    twitter_link = models.URLField( max_length=200, blank=True, null=True)
    instagram_link = models.URLField( max_length=200, blank=True, null=True)
    linked_in_link = models.URLField( max_length=200, blank=True, null=True)

    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'
    
    


    def __str__(self):
        return str(self.user)
    
class Info(models.Model):
    name = models.CharField(max_length=30)
    logo = models.ImageField(upload_to="company/")
    fb_url = models.URLField(max_length=200 , blank=True, null=True)
    twitter_url = models.URLField(max_length=200 , blank=True, null=True)
    Instgram_url = models.URLField(max_length=200 , blank=True, null=True)
    address = models.CharField(max_length=100 , blank=True, null=True)
    phone_number = models.CharField(max_length=20 , blank=True, null=True)
    mail = models.EmailField( max_length=254, blank=True, null=True)


    class Meta:
        verbose_name = ("Info")
        verbose_name_plural = ("Info")

        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("Info_detail", kwargs={"pk": self.pk})

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class NewsLitter(models.Model):
    email = models.EmailField( max_length=254)
    created_at = models.DateTimeField(default=timezone.now)
    

    class Meta:
        verbose_name = ("NewsLitter")
        verbose_name_plural = ("NewsLitter")

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email',"password1","password2"]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number','address','image','bio','phone_number','headline','fb_link' ,'twitter_link' , 'instagram_link' , 'linked_in_link']
        def __init__(self, *args, **kwargs):
            super(ProfileForm, self).__init__(*args, **kwargs)
            self.fields['image'].required = True

accounts/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .forms import SignupForm , UserForm , ProfileForm
from .models import Profile ,NewsLitter , Info
from notes_app.models import Note
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login 
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.urls import reverse



@login_required(login_url='login')
def home(request):
        user = request.user
        recent_notes = Note.objects.filter(user=user).order_by('-craeted')[:3]

        return render(request, 'home.html',{
            'user' : user ,
            'recent_notes' : recent_notes,
        })
            

def signup(request):
    if request.method == "POST":
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            usernames = form.cleaned_data['username']
            passwords = form.cleaned_data["password1"]
            user = authenticate(username=usernames,password=passwords)
            login(request,user)

            return redirect('/accounts/login')
     
    else:
        form=SignupForm()

    return render(request,'registration/signup.html',{'form':form})

def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('registration/password_reset_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect(reverse('accounts:forgotPassword'))
    return render(request, 'registration/password_reset_form.html')

def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password')
        return redirect(reverse('accounts:resetPassword'))
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('login')
    
def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect(reverse('accounts:resetPassword'))
    else:
        return render(request, 'registration/resetPassword.html')
    

def profile(request ):
    profile = Profile.objects.get(user=request.user)

    return render(request,'profile/users-profile.html',{'profile':profile})


def edit_profile(requset):
    profile = Profile.objects.get(user=requset.user)
    if requset.method == "POST":
        user_form = UserForm(requset.POST , instance=requset.user)
        profile_form = ProfileForm(requset.POST,requset.FILES,instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            myprofile = profile_form.save(commit=False)
            myprofile.user = requset.user
            myprofile.save()
            messages.success(requset, "Profile Is Updated Succssefully.")
            return redirect('/')
    else:
        user_form = UserForm(instance=requset.user)
        profile_form = ProfileForm(instance=profile)

    return render(requset,'profile/profile_edit.html',{
        'user_form':user_form,
        'profile_form':profile_form
    })


def news_letters_subscribe(request):
    email = request.POST.get('emailinput')
    NewsLitter.objects.create(email=email)
    return JsonResponse({'done':'done'})

accounts/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<br><br><br>
<div class="container"><br>
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:edit_profile'%}">User Profile</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Profile</li>
      </ol>
    </nav>
    <div class="add_form">

        <div class="col-md-6 mx-auto mt-5">
            <h2 style="text-align:center;">Edit Profile</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form user_form %}
                {% bootstrap_form profile_form %}
                {% bootstrap_button button_type="submit" content="Edit Profile" %}
            </form>

        </div>

    </div>
</div>
<br><br><br>
{% endblock body %}

accounts/templates/profile/users-profile.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}

<br><br><br><br><br>
<div class="container">
  <div class="main-body">

    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">User Profile</li>
      </ol>
    </nav>
    <!-- /Breadcrumb -->

    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              {% if profile.image %}
              <img src="{{profile.image.url}}" alt="Admin" class="rounded-circle" width="150">
              {% else %}
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                width="150">
              {% endif %}
              <div class="mt-3">
                <h4>{{profile.full_name}}</h4>
                <p class="text-muted mb-1">{{profile.headline}}</p>
                <p class="text-muted font-size-sm">{{profile.address}}</p>
                <a href="{% url 'notes_app:post_list' %}" class="btn btn-primary">My Notes</a>
                <a href="{% url 'notes_app:add_note' %}" class="btn btn-outline-primary">Add Notes<span
                                        class="badge"></span></a>
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-twitter mr-2 icon-inline text-info">
                  <path
                    d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z">
                  </path>
                </svg>Twitter</h6>
              <span class="text-muted"><a href="{{profile.twitter_link}}">{{profile.twitter_link}}</a></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-instagram mr-2 icon-inline text-danger">
                  <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                </svg>Instagram</h6>
              <span class="text-muted"><a href="{{profile.instagram_link}}">{{profile.instagram_link}}</a></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-facebook mr-2 icon-inline text-primary">
                  <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                </svg>Facebook</h6>
              <span class="text-muted"><a href="{{profile.fb_link}}">{{profile.fb_link}}</a></span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Full Name</h6>
              </div>
              <div class="col-sm-9 text-muted">
                {{profile.full_name}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">UserName</h6>
              </div>
              <div class="col-sm-9 text-muted">
                {{profile.user.username}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-muted">
                {{profile.user.email}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9 text-muted">
                {{profile.phone_number}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Address</h6>
              </div>
              <div class="col-sm-9 text-muted">
                {{profile.address}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <a class="btn btn-primary " target="__blank" href="{% url 'accounts:edit_profile'%}">Edit</a>
              </div>
            </div>
          </div>
        </div>

        <div class="row gutters-sm">
          <div class="col-sm-12 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3">About</h6>
                <p>{{profile.about}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<br><br><br>

{% endblock body %}