accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'

urlpatterns = [
    path('', views.home ,name = 'home'),
    path('signup' , views.signup , name='signup'),
    path('profile/' , views.profile , name='profile'),
    path('profile/edit' , views.edit_profile , name='edit_profile'),
    path('newsletter/' , views.news_letters_subscribe , name = 'newsletter'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
]

notes/urls.py
from django.contrib import admin
from django.urls import path , include , re_path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , include('accounts.urls',namespace='home')),
    path('notes/' , include('notes_app.urls' ,namespace = 'notes') ),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_app/urls.py
from django.urls import path , include , re_path as url

from . import views
from . import api_views

app_name = 'notes_app'

urlpatterns = [
    path('' , views.notelist , name='post_list'),
    path('id=<int:id>/' , views.post_details , name='post_detail'),
    path('tags/<str:slug>' , views.PostByTags.as_view() , name='post_by_tags'),
    path('add/' ,views.note_add , name='add_note'),
    path('<int:id>/edit' , views.edit,name='note_edit'),
    path('<int:id>/delete' , views.delete_note,name='delete_note'),
    ## api urls ##
    path('api/list' , api_views.NotesListApi.as_view(), name='notes_api_list'),
    # path('api/list' , api_views.post_list, name='notes_api_list'),
    # path('api/list/<int:id>' , api_views.post_deatils_api, name='notes_api_details'),
    # path('api/list/<str:query>' , api_views.searchByTag, name='searchByTag'),
    path('api/list/<int:pk>' , api_views.NotesDetailsApi.as_view(), name='notes_api_detail')
    
]

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Blog - HeroBiz Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

    <!-- Variables CSS Files. Uncomment your preferred color scheme -->
    <link href="{% static 'assets/css/variables.css'%}" rel="stylesheet">
    <!-- <link href="{% static 'assets/css/variables-blue.css'%}" rel="stylesheet"> -->
    <!-- <link href="{% static 'assets/css/variables-green.css'%}" rel="stylesheet"> -->
    <!-- <link href="{% static 'assets/css/variables-orange.css'%}" rel="stylesheet"> -->
    <!-- <link href="{% static 'assets/css/variables-purple.css'%}" rel="stylesheet"> -->
    <!-- <link href="{% static 'assets/css/variables-red.css'%}" rel="stylesheet"> -->
    <!-- <link href="{% static 'assets/css/variables-pink.css'%}" rel="stylesheet"> -->

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/main.css'%}" rel="stylesheet">
    <link href="{% static 'assets/css/my_style.css'%}" rel="stylesheet">

    <style>
        .messages {
            margin-top: 85px;
        }
    </style>
    <!-- =======================================================
  * Template Name: HeroBiz
  * Updated: Jul 27 2023 with Bootstrap v5.3.1
  * Template URL: https://bootstrapmade.com/herobiz-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top" data-scrollto-offset="0">
        <div class="container-fluid d-flex align-items-center justify-content-between">

            <a href="/" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1>Quick Notes<span>.</span></h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>

                    <li><a class="nav-link scrollto {% if request.path == '/' %}active {% else %}{% endif %} " href="/">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a class="nav-link scrollto {% if request.path == '/notes/' %}active {% else %}{% endif %}" href="{% url 'notes_app:post_list' %}">Notes</a></li>
                    <li><a class="nav-link scrollto {% if request.path == '/accounts/profile/' %}active {% else %}{% endif %}" href="{% url 'accounts:profile' %}">Profile</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="nav-link scrollto" href="{% url 'login' %}">Login</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle d-none"></i>
            </nav><!-- .navbar -->
            {% if request.user.is_authenticated %}
            <a class="btn-getstarted scrollto" href="{% url 'notes_app:add_note' %}">Get Started</a>
            {% endif %}

        </div>
    </header><!-- End Header -->



    {% if messages %}
    <div class="messages">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {% for message in messages %}
            <strong>success!</strong> {{ message }}
            {% endfor %}

        </div>
    </div>
    {% endif %}
    {% block body %}
    {% endblock body %}

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <h3>{{myfooter.name}}</h3>
                            <p>
                                {{myfooter.address}} <br><br><br>
                                <strong>Phone:</strong>{{myfooter.phone_number}}<br>
                                <strong>Email:</strong>{{myfooter.mail}}<br>
                            </p>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="/">Home</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div id="main_form_div" class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form id="newsletters_form" action="{% url 'home:newsletter' %}" class="subscribe-form"
                            method="POST">
                            {% csrf_token %}
                            <input type="email" name="emailinput" class="form-control"><input type="submit"
                                value="Subscribe">
                        </form>

                    </div>
                    <div id="success_div" style="display: none;" class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Subcribed Successfuly</h4>
                    </div>
                </div>
            </div>

            <div class="footer-legal text-center">
                <div
                    class="container d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between align-items-center">

                    <div class="d-flex flex-column align-items-center align-items-lg-start">
                        <div class="copyright">
                            &copy; Copyright <strong><span>HeroBiz</span></strong>. All Rights Reserved
                        </div>
                        <div class="credits">
                            <!-- All the links in the footer should remain intact. -->
                            <!-- You can delete the links only if you purchased the pro version. -->
                            <!-- Licensing information: https://bootstrapmade.com/license/ -->
                            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
                            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                        </div>
                    </div>

                    <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
                        <a href="{{myfooter.twitter_url}}" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="{{myfooter.fb_url}}" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="{{myfooter.Instgram_url}}" class="instagram"><i class="bi bi-instagram"></i></a>
                    </div>

                </div>
            </div>

    </footer><!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script>
        $("#newsletters_form").submit(function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr('action');

            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(),
                success: function (data) {
                    document.getElementById('main_form_div').style.display = "none";
                    document.getElementById('success_div').style.display = "block";
                }
            })
        })
    </script>

</body>

</html>